name: update-bot

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 23 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_new: ${{ steps.check_ver.outputs.is_new }}
      img_ver: ${{ steps.check_ver.outputs.img_ver }}
      qbt_ver: ${{ steps.check_ver.outputs.qbt_ver }}
      lib_ver: ${{ steps.check_ver.outputs.lib_ver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check version
        id: check_ver
        run: |
          NEW_TAG=$(curl -s "${REPO_TAGS}" | grep -Po "release-(\d+\.){2}\d+\.zip" | head -1)
          LIB_VER=$(jq -r '.libtorrent' ./latest.json)
          QBT_VER=$(jq -r '.qbittorrent' ./latest.json)
          PKG_REL=$(jq -r '.pkgrel' ./latest.json)
          if [ ${{ github.event_name }} == 'push' ]; then
            echo "::set-output name=img_ver::${QBT_VER}-r${PKG_REL}"
            echo "::set-output name=qbt_ver::${QBT_VER}"
            echo "::set-output name=is_new::yes"
          elif [ "${NEW_TAG:8:5}" != "${QBT_VER}" ]; then
            echo "::set-output name=img_ver::${NEW_TAG:8:5}-r0"
            echo "::set-output name=qbt_ver::${NEW_TAG:8:5}"
            echo "::set-output name=is_new::yes"
          else
            echo "::set-output name=is_new::no"
          fi
          echo "::set-output name=lib_ver::${LIB_VER}"
        env:
          REPO_TAGS: https://github.com/qbittorrent/qBittorrent/tags

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.is_new == 'yes' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: |
            ${{ github.repository_owner }}/qbittorrent
            ghcr.io/${{ github.repository_owner }}/qbittorrent
          tags: |
            type=edge
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,${{ needs.check.outputs.img_ver }}
            type=raw,latest

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            QBITTORRENT_VERSION=${{ needs.check.outputs.qbt_ver }}
            LIBTORRENT_VERSION=${{ needs.check.outputs.lib_ver }}

      - name: Save metadata
        run: echo ${{ toJSON(steps.build.outputs.metadata) }} > ${{ github.workspace }}/meta.json

      - name: Update metadata
        uses: actions/upload-artifact@v2
        with:
          name: metadata
          path: ${{ github.workspace }}/meta.json
